formatter: "markdown table"

output:
  file: "README.md"
  mode: "inject"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  html: true
  indent: 2
  lockfile: false
  
sections:
  show:
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

content: |-
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

  ## Examples

  ### Basic
  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  ### PostGIS
  ```hcl
  {{ include "examples/postgis/main.tf" }}
  ```
